name: Compile and Run Test
on: [push]
jobs:
  test-module-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update
      - run: sudo apt install build-essential cmake extra-cmake-modules qt5-default libkf5parts-dev libkf5texteditor-dev libpoppler-qt5-dev libpoppler-cpp-dev libpoppler-glib-dev kdelibs5-dev ktexteditor-katepart gettext xvfb
      - run: mkdir build && cd build && cmake .. && make
      - run: xvfb-run --auto-servernum --server-num=1 ./livetikz --version | grep -c livetikz
